### ISSUE TITLE
Consider add an icon for the mod "score v2"?

### ISSUE THREAD

**Issue by m13253** [mrlinuxfish/FishMix#1]
Hello, I love your FishMix skin.
But I found the lack of an icon for the mod "score v2". Are you going to create one, or just wait for that mod to disappear some day in the future?

![image](https://cloud.githubusercontent.com/assets/1808930/24606733/3575c6e0-1834-11e7-9f5a-d02da21b0400.png)

Thanks.

**Comment by violet-fish** [comment]
I'm glad you found my skin. I'm planning on making new icons for all the mods in the near future. The current icons are not HD and I don't have the original versions to make them HD. 

- Added mod icons to todo

Thank for the feedback.

**Comment by violet-fish** [comment]
All mods should have icons now in v2.1.
